//
//  ReporterFormNavWrapper.swift
//  SimpleLogger
//
//  Created by Pedro Cavaleiro on 14/09/2025.
//
//  Docs Generated by Claude Sonnet 4
//

import SwiftUI

/// A navigation wrapper view that provides a NavigationStack container for the bug reporting form.
///
/// `ReporterFormNavWrapper` is a convenience view that wraps ``ReporterFormView`` within a
/// `NavigationStack`, providing the necessary navigation context for the bug reporting interface.
/// This wrapper is useful when you need to present the reporter form in contexts where a
/// navigation container is required but not already present.
///
/// ## Overview
///
/// This wrapper serves as a bridge between the core ``ReporterFormView`` and presentation
/// contexts that require navigation functionality. It automatically provides:
/// - Navigation stack container for proper navigation behavior
/// - Seamless integration with SwiftUI's navigation system
/// - Consistent navigation appearance across different presentation contexts
///
/// ## Usage
///
/// ### Basic Usage
///
/// ```swift
/// let config = ReporterViewConfiguration(
///     sendAction: { issueText, preFilledData, customFields, logInfo in
///         // Handle the bug report submission
///         submitBugReport(issueText, preFilledData, customFields, logInfo)
///     }
/// )
///
/// ReporterFormNavWrapper(configuration: config)
/// ```
///
/// ### Presenting as a Sheet
///
/// ```swift
/// @State private var showingBugReport = false
///
/// Button("Report Bug") {
///     showingBugReport = true
/// }
/// .sheet(isPresented: $showingBugReport) {
///     let config = ReporterViewConfiguration(
///         sendAction: { issueText, preFilledData, customFields, logInfo in
///             // Handle submission and dismiss
///             submitReport(issueText, preFilledData, customFields, logInfo)
///             showingBugReport = false
///         }
///     )
///     ReporterFormNavWrapper(configuration: config)
/// }
/// ```
///
/// ### Presenting as Full Screen Cover
///
/// ```swift
/// @State private var showingBugReport = false
///
/// Button("Report Issue") {
///     showingBugReport = true
/// }
/// .fullScreenCover(isPresented: $showingBugReport) {
///     let config = ReporterViewConfiguration(
///         navigationBarTitle: "Bug Report",
///         sendAction: { issueText, preFilledData, customFields, logInfo in
///             handleBugReport(issueText, preFilledData, customFields, logInfo)
///             showingBugReport = false
///         }
///     )
///     ReporterFormNavWrapper(configuration: config)
/// }
/// ```
///
/// ## When to Use
///
/// Use `ReporterFormNavWrapper` when:
/// - Presenting the bug reporter in a sheet or full screen cover
/// - The current view hierarchy doesn't already have a NavigationStack
/// - You need a simple, one-step solution for bug reporting UI
///
/// Use ``ReporterFormView`` directly when:
/// - You're already within a NavigationStack or NavigationView
/// - You need more control over the navigation presentation
/// - You're integrating the form into an existing navigation flow
///
/// ## Important
/// The `ReporterFormNavWrapper` requires a custom `sendAction` closure to be provided in the configuration.
/// There is no default send report implementation - you must handle the report submission yourself
/// by implementing the `sendAction` closure in your `ReporterViewConfiguration`.
///
/// ## Topics
///
/// ### View Properties
///
/// - ``configuration``
/// - ``body``
///
/// ## See Also
///
/// - ``ReporterFormView``
/// - ``ReporterViewConfiguration``
public struct ReporterFormNavWrapper: View {
    
    /// The configuration object that defines the form's appearance and behavior.
    ///
    /// This constant contains all customization options for the bug reporting form, including
    /// text content, section visibility, custom fields, pre-filled data settings, and most
    /// importantly, the `sendAction` closure that handles report submission.
    ///
    /// The configuration is set during initialization and remains constant throughout
    /// the view's lifecycle. It is passed through to the underlying ``ReporterFormView``
    /// to control its behavior and appearance.
    ///
    /// ## Example
    /// ```swift
    /// let config = ReporterViewConfiguration(
    ///     navigationBarTitle: "Submit Feedback",
    ///     showPrefilledDataSection: true,
    ///     sendAction: { issueText, preFilledData, customFields, logInfo in
    ///         // Handle the bug report submission
    ///         MyReportingService.submit(
    ///             description: issueText,
    ///             deviceInfo: preFilledData,
    ///             additionalFields: customFields,
    ///             logData: logInfo
    ///         )
    ///     }
    /// )
    /// ```
    ///
    /// ## See Also
    /// - ``ReporterViewConfiguration``
    public let configuration: ReporterViewConfiguration
    
    /// Creates a new navigation wrapper for the reporter form with the specified configuration.
    ///
    /// - Parameter configuration: The configuration object that defines the form's
    ///   appearance, behavior, custom fields, and action handlers.
    public init(configuration: ReporterViewConfiguration) {
        self.configuration = configuration
    }
 
    /// The main view body that renders the navigation-wrapped bug reporting form.
    ///
    /// The body creates a `NavigationStack` that contains a ``ReporterFormView`` configured
    /// with the provided configuration object. This structure ensures that the bug reporting
    /// form has the necessary navigation context for proper operation, including:
    ///
    /// - Navigation bar with title and send button
    /// - Proper navigation behavior and animations
    /// - Integration with SwiftUI's navigation system
    ///
    /// The underlying ``ReporterFormView`` handles all the form logic, data collection,
    /// and report submission through the configuration's `sendAction` closure.
    ///
    /// ## Navigation Structure
    /// ```
    /// NavigationStack
    /// └── ReporterFormView
    ///     ├── Bug Description Section
    ///     ├── Custom Fields Section (optional)
    ///     ├── Pre-filled Data Section (optional)
    ///     └── Log Files Information Section (optional)
    /// ```
    public var body: some View {
        NavigationStack {
            ReporterFormView(configuration: configuration)
        }
    }
    
}
